In [1]:
!pip install -q mlflow dagshub

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 2.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.5/50.5 kB 4.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.6/12.6 MB 110.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 123.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 88.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 273.3/273.3 kB 25.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.7/264.7 kB 26.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 105.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.2/68.2 kB 7.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.8/148.8 kB 14.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 13.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 21.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.3/121.3 kB 12.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.2/132.2 kB 13.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.0/140.0 kB 14.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.4/15.4 MB 105.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 969.1/969.1 kB 58.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.9/214.9 kB 21.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.0/51.0 kB 5.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 kB 9.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.9/89.9 kB 9.8 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pyopenssl 26.3.0 requires cryptography<50,>=49.0.0, but you have cryptography 48.0.1 which is incompatible.

In [2]:
import os
import re
import json
import random
from collections import Counter
from pathlib import Path
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.callbacks import (EarlyStopping, ModelCheckpoint,ReduceLROnPlateau)
import mlflow
import dagshub

In [3]:
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

os.environ["PYTHONHASHSEED"] = str(SEED)

In [4]:
mlflow.set_tracking_uri("https://dagshub.com/Ahmad450-gcu/Next-Word-Predictor.mlflow")

In [5]:
import dagshub
dagshub.init(repo_owner='Ahmad450-gcu', repo_name='Next-Word-Predictor', mlflow=True)
mlflow.set_experiment("WikiText2_Baseline_Preprocessing")

                                       ❗❗❗ AUTHORIZATION REQUIRED ❗❗❗

Output()

Open the following link in your browser to authorize the client:
https://dagshub.com/login/oauth/authorize?state=b7b64653-018e-4ee1-9e18-17c95e89d7ad&client_id=32b60ba385aa7cecf24046d8195a71c07dd345d9657977863b52e7748e0f0f28&middleman_request_id=e4673cb40c75f738de385c1ee8e364a938ab7a56ada1b38c6a1fa4947c482f00

Accessing as Ahmad450-gcu

Initialized MLflow to track repo "Ahmad450-gcu/Next-Word-Predictor"

Repository Ahmad450-gcu/Next-Word-Predictor initialized!

<Experiment: artifact_location='mlflow-artifacts:/bd5eb7154e254e0983676b72654e1157', creation_time=1785056889924, effective_trace_archival_retention=None, experiment_id='1', last_update_time=1785056889924, lifecycle_stage='active', name='WikiText2_Baseline_Preprocessing', tags={}, trace_location=None, workspace='default'>

In [6]:
mlflow.tensorflow.autolog(log_models=True, checkpoint=False)

In [7]:
config = {

    # Preprocessing
    "remove_whitespace": True,
    "remove_headings": False,
    "lowercase": False,
    "normalize_wikitext": False,
    "min_frequency": 5,

    # Sequence Generation
    "sequence_length": 20,

    # Model
    "embedding_dim": 128,
    "lstm_units": 256,

    # Training
    "batch_size": 64,
    "epochs": 10,
    "learning_rate": 0.001,

    # Random Seed
    "seed": SEED
}

In [8]:
mlflow.start_run(run_name="Experiment_01_Baseline")
mlflow.log_params(config)

In [9]:
# Loading dataset
with open("wiki.train.raw", "r", encoding="utf-8") as f:
    train_data = f.readlines()
with open("wiki.valid.raw", "r", encoding="utf-8") as f:
    valid_data = f.readlines()
with open("wiki.test.raw", "r", encoding="utf-8") as f:
    test_data = f.readlines()
print(f"Train : {len(train_data):,} lines")
print(f"Valid : {len(valid_data):,} lines")
print(f"Test  : {len(test_data):,} lines")

Train : 36,718 lines
Valid : 3,760 lines
Test  : 4,358 lines

In [10]:
# split corpus into individual articles with whitespaces as seperators
def split_articles(lines):
    articles = []
    current_article = []
    for line in lines:
        line = line.strip()
        if line == "":
            if current_article:
                articles.append(current_article)
                current_article = []
        else:
            current_article.append(line)
    if current_article:
        articles.append(current_article)
    return articles

In [11]:
train_articles = split_articles(train_data)
valid_articles = split_articles(valid_data)
test_articles = split_articles(test_data)

In [12]:
print(f"Train Articles : {len(train_articles):,}")
print(f"Valid Articles : {len(valid_articles):,}")
print(f"Test Articles  : {len(test_articles):,}")

Train Articles : 11,669
Valid Articles : 1,160
Test Articles  : 1,320

In [13]:
mlflow.log_metric("train_articles", len(train_articles))
mlflow.log_metric("valid_articles", len(valid_articles))
mlflow.log_metric("test_articles", len(test_articles))

In [14]:
def articles_to_text(articles):
    article_texts = []
    for article in articles:
        text = " ".join(article)
        article_texts.append(text)
    return article_texts

In [15]:
train_texts = articles_to_text(train_articles)
valid_texts = articles_to_text(valid_articles)
test_texts = articles_to_text(test_articles)

In [16]:
print("Number of training articles:", len(train_texts))
print("\nFirst training article:\n")
print(train_texts[:10][:100])   # Print first 1000 characters

Number of training articles: 11669

First training article:

['= Valkyria Chronicles III =', 'Senjō no Valkyria 3 : Unrecorded Chronicles ( Japanese : 戦場のヴァルキュリア3 , lit . Valkyria of the Battlefield 3 ) , commonly referred to as Valkyria Chronicles III outside Japan , is a tactical role @-@ playing video game developed by Sega and Media.Vision for the PlayStation Portable . Released in January 2011 in Japan , it is the third game in the Valkyria series . Employing the same fusion of tactical and real @-@ time gameplay as its predecessors , the story runs parallel to the first game and follows the " Nameless " , a penal military unit serving the nation of Gallia during the Second Europan War who perform secret black operations and are pitted against the Imperial unit " Calamaty Raven " . The game began development in 2010 , carrying over a large portion of the work done on Valkyria Chronicles II . While it retained the standard features of the series , it also underwent multiple adjustments , such as making the game more forgiving for series newcomers . Character designer Raita Honjou and composer Hitoshi Sakimoto both returned from previous entries , along with Valkyria Chronicles II director Takeshi Ozawa . A large team of writers handled the script . The game \'s opening theme was sung by May \'n . It met with positive sales in Japan , and was praised by both Japanese and western critics . After release , it received downloadable content , along with an expanded edition in November of that year . It was also adapted into manga and an original video animation series . Due to low sales of Valkyria Chronicles II , Valkyria Chronicles III was not localized , but a fan translation compatible with the game \'s expanded edition was released in 2014 . Media.Vision would return to the franchise with the development of Valkyria : Azure Revolution for the PlayStation 4 .', '= = Gameplay = =', 'As with previous Valkyira Chronicles games , Valkyria Chronicles III is a tactical role @-@ playing game where players take control of a military unit and take part in missions against enemy forces . Stories are told through comic book @-@ like panels with animated character portraits , with characters speaking partially through voiced speech bubbles and partially through unvoiced text . The player progresses through a series of linear missions , gradually unlocked as maps that can be freely scanned through and replayed as they are unlocked . The route to each story location on the map varies depending on an individual player \'s approach : when one option is selected , the other is sealed off to the player . Outside missions , the player characters rest in a camp , where units can be customized and character growth occurs . Alongside the main story missions are character @-@ specific sub missions relating to different squad members . After the game \'s completion , additional episodes are unlocked , some of them having a higher difficulty than those found in the rest of the game . There are also love simulation elements related to the game \'s two main heroines , although they take a very minor role . The game \'s battle system , the BliTZ system , is carried over directly from Valkyira Chronicles . During missions , players select each unit using a top @-@ down perspective of the battlefield map : once a character is selected , the player moves the character around the battlefield in third @-@ person . A character can only act once per @-@ turn , but characters can be granted multiple turns at the expense of other characters \' turns . Each character has a field and distance of movement limited by their Action Gauge . Up to nine characters can be assigned to a single mission . During gameplay , characters will call out if something happens to them , such as their health points ( HP ) getting low or being knocked out by enemy attacks . Each character has specific " Potentials " , skills unique to each character . They are divided into " Personal Potential " , which are innate skills that remain unaltered unless otherwise dictated by the story and can either help or impede a character , and " Battle Potentials " , which are grown throughout the game and always grant boons to a character . To learn Battle Potentials , each character has a unique " Masters Table " , a grid @-@ based skill table that can be used to acquire and link different skills . Characters also have Special Abilities that grant them temporary boosts on the battlefield : Kurt can activate " Direct Command " and move around the battlefield without depleting his Action Point gauge , the character Reila can shift into her " Valkyria Form " and become invincible , while Imca can target multiple enemy units with her heavy weapon . Troops are divided into five classes : Scouts , Shocktroopers , Engineers , Lancers and Armored Soldier . Troopers can switch classes by changing their assigned weapon . Changing class does not greatly affect the stats gained while in a previous class . With victory in battle , experience points are awarded to the squad , which are distributed into five different attributes shared by the entire squad , a feature differing from early games \' method of distributing to different unit types .', '= = Plot = =', 'The game takes place during the Second Europan War . Gallian Army Squad 422 , also known as " The Nameless " , are a penal military unit composed of criminals , foreign deserters , and military offenders whose real names are erased from the records and thereon officially referred to by numbers . Ordered by the Gallian military to perform the most dangerous missions that the Regular Army and Militia will not do , they are nevertheless up to the task , exemplified by their motto , Altaha Abilia , meaning " Always Ready . " The three main characters are No.7 Kurt Irving , an army officer falsely accused of treason who wishes to redeem himself ; Ace No.1 Imca , a female Darcsen heavy weapons specialist who seeks revenge against the Valkyria who destroyed her home ; and No.13 Riela Marcellis , a seemingly jinxed young woman who is unknowingly a descendant of the Valkyria . Together with their fellow squad members , these three are tasked to fight against a mysterious Imperial unit known as Calamity Raven , consisting of mostly Darcsen soldiers . As the Nameless officially do not exist , the upper echelons of the Gallian Army exploit the concept of plausible deniability in order to send them on missions that would otherwise make Gallia lose face in the war . While at times this works to their advantage , such as a successful incursion into Imperial territory , other orders cause certain members of the 422nd great distress . One such member , Gusurg , becomes so enraged that he abandons his post and defects into the ranks of Calamity Raven , attached to the ideal of Darcsen independence proposed by their leader , Dahau . At the same time , elements within Gallian Army Command move to erase the Nameless in order to protect their own interests . Hounded by both allies and enemies , and combined with the presence of a traitor within their ranks , the 422nd desperately move to keep themselves alive while at the same time fight to help the Gallian war effort . This continues until the Nameless \'s commanding officer , Ramsey Crowe , who had been kept under house arrest , is escorted to the capital city of Randgriz in order to present evidence exonerating the weary soldiers and expose the real traitor , the Gallian General that had accused Kurt of Treason . Partly due to these events , and partly due to the major losses in manpower Gallia suffers towards the end of the war with the Empire , the Nameless are offered a formal position as a squad in the Gallian Army rather than serve as an anonymous shadow force . This is short @-@ lived , however , as following Maximilian \'s defeat , Dahau and Calamity Raven move to activate an ancient Valkyrian super weapon within the Empire , kept secret by their benefactor . Without the support of Maximilian or the chance to prove themselves in the war with Gallia , it is Dahau \'s last trump card in creating a new Darcsen nation . As an armed Gallian force invading the Empire just following the two nations \' cease @-@ fire would certainly wreck their newfound peace , Kurt decides to once again make his squad the Nameless , asking Crowe to list himself and all under his command as killed @-@ in @-@ action . Now owing allegiance to none other than themselves , the 422nd confronts Dahau and destroys the Valkyrian weapon . Each member then goes their separate ways in order to begin their lives anew .', '= = Development = =', 'Concept work for Valkyria Chronicles III began after development finished on Valkyria Chronicles II in early 2010 , with full development beginning shortly after this . The director of Valkyria Chronicles II , Takeshi Ozawa , returned to that role for Valkyria Chronicles III . Development work took approximately one year . After the release of Valkyria Chronicles II , the staff took a look at both the popular response for the game and what they wanted to do next for the series . Like its predecessor , Valkyria Chronicles III was developed for PlayStation Portable : this was due to the team wanting to refine the mechanics created for Valkyria Chronicles II , and they had not come up with the " revolutionary " idea that would warrant a new entry for the PlayStation 3 . Speaking in an interview , it was stated that the development team considered Valkyria Chronicles III to be the series \' first true sequel : while Valkyria Chronicles II had required a large amount of trial and error during development due to the platform move , the third game gave them a chance to improve upon the best parts of Valkyria Chronicles II due to being on the same platform . In addition to Sega staff from the previous games , development work was also handled by Media.Vision. The original scenario was written Kazuki Yamanobe , while the script was written by Hiroyuki Fujii , Koichi Majima , Kishiko Miyagi , Seiki Nagakawa and Takayuki Shouji . Its story was darker and more somber than that of its predecessor . The majority of material created for previous games , such as the BLiTZ system and the design of maps , was carried over . Alongside this , improvements were made to the game \'s graphics and some elements were expanded , such as map layouts , mission structure , and the number of playable units per mission . A part of this upgrade involved creating unique polygon models for each character \'s body . In order to achieve this , the cooperative elements incorporated into the second game were removed , as they took up a large portion of memory space needed for the improvements . They also adjusted the difficulty settings and ease of play so they could appeal to new players while retaining the essential components of the series \' gameplay . The newer systems were decided upon early in development . The character designs were done by Raita Honjou , who had worked on the previous Valkyria Chronicles games . When creating the Nameless Squad , Honjou was faced with the same problem he had had during the first game : the military uniforms essentially destroyed character individuality , despite him needing to create unique characters the player could identify while maintaining a sense of reality within the Valkyria Chronicles world . The main color of the Nameless was black . As with the previous Valkyria games , Valkyria Chronicles III used the CANVAS graphics engine . The anime opening was produced by Production I.G.', '= = = Music = = =', 'The music was composed by Hitoshi Sakimoto , who had also worked on the previous Valkyria Chronicles games . When he originally heard about the project , he thought it would be a light tone similar to other Valkyria Chronicles games , but found the themes much darker than expected . An early theme he designed around his original vision of the project was rejected . He redid the main theme about seven times through the music production due to this need to reassess the game . The main theme was initially recorded using orchestra , then Sakimoto removed elements such as the guitar and bass , then adjusted the theme using a synthesizer before redoing segments such as the guitar piece on their own before incorporating them into the theme . The rejected main theme was used as a hopeful tune that played during the game \'s ending . The battle themes were designed around the concept of a " modern battle " divorced from a fantasy scenario by using modern musical instruments , constructed to create a sense of atonality . While Sakimoto was most used to working with synthesized music , he felt that he needed to incorporate live instruments such as orchestra and guitar . The guitar was played by Mitsuhiro Ohta , who also arranged several of the later tracks . The game \'s opening theme song , " If You Wish for ... " ( もしも君が願うのなら , Moshimo Kimi ga Negauno Nara ) , was sung by Japanese singer May \'n . Its theme was the reason soldiers fought , in particular their wish to protect what was precious to them rather than a sense of responsibility or duty . Its lyrics were written by Seiko Fujibayashi , who had worked on May \'n on previous singles .']

In [17]:
train_characters = sum(len(text) for text in train_texts)
valid_characters = sum(len(text) for text in valid_texts)
test_characters = sum(len(text) for text in test_texts)
print(f"Train Characters : {train_characters:,}")
print(f"Valid Characters : {valid_characters:,}")
print(f"Test Characters  : {test_characters:,}")

Train Characters : 10,833,784
Valid Characters : 1,136,065
Test Characters  : 1,278,520

In [18]:
mlflow.log_metrics({
    "train_articles": len(train_texts),
    "valid_articles": len(valid_texts),
    "test_articles": len(test_texts),
    "train_characters": train_characters,
    "valid_characters": valid_characters,
    "test_characters": test_characters
})

In [19]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(lower=False, filters="", oov_token="<UNK>")
tokenizer.fit_on_texts(train_texts)

In [68]:
vocab_size = len(tokenizer.word_index) + 1
print(f"Vocabulary Size: {vocab_size:,}")
print("\nFirst 20 Vocabulary Entries:\n")
for word, idx in list(tokenizer.word_index.items())[:20]:
    print(f"{idx:>5} : {word}")

Vocabulary Size: 76,618

First 20 Vocabulary Entries:

    1 : <UNK>
    2 : the
    3 : ,
    4 : .
    5 : of
    6 : and
    7 : in
    8 : to
    9 : a
   10 : =
   11 : "
   12 : was
   13 : The
   14 : @-@
   15 : that
   16 : as
   17 : 's
   18 : on
   19 : for
   20 : with

In [71]:
mlflow.log_param("lowercase", False)
mlflow.log_param("filters", "")
mlflow.log_param("oov_token", "<UNK>")
mlflow.log_metric("vocabulary_size", vocab_size)

In [72]:
print("=" * 23)
print("Vocabulary Statistics")
print("=" * 23)
print(f"Vocabulary Size : {vocab_size}")

=======================
Vocabulary Statistics
=======================
Vocabulary Size : 76618

In [73]:
word_counts = tokenizer.word_counts
top_20 = sorted(word_counts.items(), key=lambda x: x[1],reverse=True)[:20]

In [74]:
top20_df = (pd.DataFrame(top_20, columns=["Word", "Frequency"]))
top20_df

    Word  Frequency
0    the     113161
1      ,      99913
2      .      73388
3     of      56889
4    and      50603
5     in      39453
6     to      39190
7      a      34237
8      =      29570
9      "      28309
10   was      20985
11   The      17602
12   @-@      16906
13  that      14135
14    as      14021
15    's      14002
16    on      13678
17   for      13307
18  with      12606
19    by      12148

In [75]:
freq_df = pd.DataFrame(
    word_counts.items(),
    columns=["Word", "Frequency"]
)

freq_df["Frequency"].describe()

count     76616.000000
mean         26.781743
std         756.143991
min           1.000000
25%           1.000000
50%           2.000000
75%           6.000000
max      113161.000000
Name: Frequency, dtype: float64

In [76]:
singleton_words = sum(1 for count in word_counts.values() if count == 1)
rare_words = sum(1 for count in word_counts.values() if count <= 5)

print(f"Singleton Words : {singleton_words:,}")
print(f"Words ≤5 Frequency : {rare_words:,}")

Singleton Words : 32,055
Words ≤5 Frequency : 55,990

In [77]:
print("OOV Token:")
print(tokenizer.oov_token)
print("\nOOV Index:")
print(tokenizer.word_index[tokenizer.oov_token])

OOV Token:
<UNK>

OOV Index:
1

In [78]:
mlflow.log_metrics({
    "vocabulary_size": vocab_size,
    "singleton_words": singleton_words,
    "rare_words_leq5": rare_words
})

In [79]:
with open("tokenizer_word_index.json", "w") as f:
    json.dump(tokenizer.word_index,f,indent=4)
mlflow.log_artifact("tokenizer_word_index.json")

In [80]:
train_sequences = tokenizer.texts_to_sequences(train_texts)
valid_sequences = tokenizer.texts_to_sequences(valid_texts)
test_sequences = tokenizer.texts_to_sequences(test_texts)

In [81]:
print("Encoded Sequence:")
print(train_sequences[10][:100])

Encoded Sequence:
[10, 10, 10, 4205, 10, 10, 10]

In [82]:
train_total_tokens = sum(len(seq) for seq in train_sequences)
valid_total_tokens = sum(len(seq) for seq in valid_sequences)
test_total_tokens = sum(len(seq) for seq in test_sequences)

print(f"Train Tokens : {train_total_tokens:,}")
print(f"Valid Tokens : {valid_total_tokens:,}")
print(f"Test Tokens  : {test_total_tokens:,}")

Train Tokens : 2,051,910
Valid Tokens : 213,886
Test Tokens  : 241,211

In [83]:
oov_index = tokenizer.word_index[tokenizer.oov_token]

train_oov = sum(token == oov_index for seq in train_sequences for token in seq)
valid_oov = sum(token == oov_index for seq in valid_sequences for token in seq)
test_oov = sum(token == oov_index for seq in test_sequences for token in seq)

print(f"Train OOV Tokens : {train_oov:,}")
print(f"Valid OOV Tokens : {valid_oov:,}")
print(f"Test OOV Tokens  : {test_oov:,}")

Train OOV Tokens : 0
Valid OOV Tokens : 7,183
Test OOV Tokens  : 9,864

In [84]:
train_oov_pct = (train_oov / train_total_tokens) * 100
valid_oov_pct = (valid_oov / valid_total_tokens) * 100
test_oov_pct = (test_oov / test_total_tokens) * 100

print(f"Train OOV % : {train_oov_pct:.4f}%")
print(f"Valid OOV % : {valid_oov_pct:.4f}%")
print(f"Test OOV %  : {test_oov_pct:.4f}%")

Train OOV % : 0.0000%
Valid OOV % : 3.3583%
Test OOV %  : 4.0894%

In [85]:
mlflow.log_metrics({
    "train_total_tokens": train_total_tokens,
    "valid_total_tokens": valid_total_tokens,
    "test_total_tokens": test_total_tokens,
    "train_oov_percent": train_oov_pct,
    "valid_oov_percent": valid_oov_pct,
    "test_oov_percent": test_oov_pct
})

In [86]:
def generate_sequences(sequences, sequence_length):
    X = []
    y = []
    for article in sequences:
        if len(article) <= sequence_length:
            continue
        for i in range(sequence_length, len(article)):
            X.append(article[i-sequence_length:i])
            y.append(article[i])
    return X, y

In [87]:
SEQUENCE_LENGTH = config["sequence_length"]
X_train, y_train = generate_sequences(train_sequences, SEQUENCE_LENGTH)
X_valid, y_valid = generate_sequences(valid_sequences, SEQUENCE_LENGTH)
X_test, y_test = generate_sequences(test_sequences,SEQUENCE_LENGTH)

In [88]:
print(f"Training Samples   : {len(X_train):,}")
print(f"Validation Samples : {len(X_valid):,}")
print(f"Test Samples       : {len(X_test):,}")

Training Samples   : 1,898,620
Validation Samples : 198,603
Test Samples       : 223,641

In [89]:
sample = 0
print("Input IDs:\n")
print(X_train[sample])
print("\nTarget ID:\n")
print(y_train[sample])

Input IDs:

[20628, 127, 3908, 90, 43, 44563, 4419, 23, 752, 43, 27246, 3, 7036, 4, 3908, 5, 2, 23380, 90, 22]

Target ID:

3

In [90]:
index_word = tokenizer.index_word
sample = 9
decoded_input = [index_word.get(idx, "<UNK>") for idx in X_train[sample]]
decoded_target = index_word.get(y_train[sample],"<UNK>")

print("Input:\n")
print(decoded_input)
print("\nTarget:\n")
print(decoded_target)

Input:

[':', '戦場のヴァルキュリア3', ',', 'lit', '.', 'Valkyria', 'of', 'the', 'Battlefield', '3', ')', ',', 'commonly', 'referred', 'to', 'as', 'Valkyria', 'Chronicles', 'III', 'outside']

Target:

Japan

In [91]:
mlflow.log_metrics({
    "train_samples": len(X_train),
    "valid_samples": len(X_valid),
    "test_samples": len(X_test),
    "sequence_length": SEQUENCE_LENGTH
})

In [92]:
X_train = np.array(X_train, dtype=np.int32)
y_train = np.array(y_train, dtype=np.int32)

X_valid = np.array(X_valid, dtype=np.int32)
y_valid = np.array(y_valid, dtype=np.int32)

X_test = np.array(X_test, dtype=np.int32)
y_test = np.array(y_test, dtype=np.int32)

In [93]:
assert X_train.max() < vocab_size, f"X_train has index {X_train.max()} >= vocab_size {vocab_size}"
assert y_train.max() < vocab_size, f"y_train has index {y_train.max()} >= vocab_size {vocab_size}"

In [94]:
print("=" * 60)
print("Dataset Shapes")
print("=" * 60)

print(f"X_train : {X_train.shape}")
print(f"y_train : {y_train.shape}")

print(f"\nX_valid : {X_valid.shape}")
print(f"y_valid : {y_valid.shape}")

print(f"\nX_test  : {X_test.shape}")
print(f"y_test  : {y_test.shape}")

============================================================
Dataset Shapes
============================================================
X_train : (1898620, 20)
y_train : (1898620,)

X_valid : (198603, 20)
y_valid : (198603,)

X_test  : (223641, 20)
y_test  : (223641,)

In [95]:
print(f"X_train Memory : {X_train.nbytes / 1024**2:.2f} MB")
print(f"y_train Memory : {y_train.nbytes / 1024**2:.2f} MB")

print(f"X_valid Memory : {X_valid.nbytes / 1024**2:.2f} MB")
print(f"y_valid Memory : {y_valid.nbytes / 1024**2:.2f} MB")

print(f"X_test Memory  : {X_test.nbytes / 1024**2:.2f} MB")
print(f"y_test Memory  : {y_test.nbytes / 1024**2:.2f} MB")

X_train Memory : 144.85 MB
y_train Memory : 7.24 MB
X_valid Memory : 15.15 MB
y_valid Memory : 0.76 MB
X_test Memory  : 17.06 MB
y_test Memory  : 0.85 MB

In [96]:
mlflow.log_metrics({
    "num_train_samples": X_train.shape[0],
    "num_valid_samples": X_valid.shape[0],
    "num_test_samples": X_test.shape[0],

    "sequence_length": X_train.shape[1],

    "vocab_size": vocab_size
})

In [97]:
BATCH_SIZE = config["batch_size"]
train_dataset = (
    tf.data.Dataset
    .from_tensor_slices((X_train, y_train))
    .shuffle(
        buffer_size=len(X_train),
        seed=SEED,
        reshuffle_each_iteration=True
    )
    .batch(BATCH_SIZE)
    .cache()
    .prefetch(tf.data.AUTOTUNE)
)

In [98]:
valid_dataset = (
    tf.data.Dataset
    .from_tensor_slices((X_valid, y_valid))
    .batch(BATCH_SIZE)
    .cache()
    .prefetch(tf.data.AUTOTUNE)
)

In [99]:
test_dataset = (
    tf.data.Dataset
    .from_tensor_slices((X_test, y_test))
    .batch(BATCH_SIZE)
    .cache()
    .prefetch(tf.data.AUTOTUNE)
)

In [100]:
for batch_x, batch_y in train_dataset.take(1):
    print("Input Shape :", batch_x.shape)
    print("Target Shape:", batch_y.shape)

    print("\nFirst Input Sequence:")
    print(batch_x[0].numpy())

    print("\nFirst Target:")
    print(batch_y[0].numpy())

Input Shape : (64, 20)
Target Shape: (64,)

First Input Sequence:
[  12  194  170    3 1760    2  602  775    4 2115 1484    6 1103    3
 1749  693   45  417 6233   21]

First Target:
244

In [101]:
mlflow.log_params({"batch_size": BATCH_SIZE})

mlflow.log_metrics({
    "train_batches": len(train_dataset),
    "valid_batches": len(valid_dataset),
    "test_batches": len(test_dataset)
})

# Making a baseline model to test different preprocessing experimnts, will improve the architecture later on

In [102]:
# Defining some contsnats
VOCAB_SIZE = vocab_size
EMBEDDING_DIM = config["embedding_dim"]
LSTM_UNITS = config["lstm_units"]
SEQUENCE_LENGTH = config["sequence_length"]
LEARNING_RATE = config["learning_rate"]

In [103]:
model = Sequential()
model.add(Embedding(input_dim=VOCAB_SIZE, output_dim=EMBEDDING_DIM, input_length=SEQUENCE_LENGTH, name="embedding"))
model.add(LSTM(units=LSTM_UNITS, name="lstm"))
model.add(Dense(units=VOCAB_SIZE, activation="softmax", name="output"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [104]:
optimizer = tf.keras.optimizers.Adam(learning_rate=LEARNING_RATE)
model.compile(optimizer=optimizer, loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [105]:
model.build(input_shape=(None, SEQUENCE_LENGTH))

In [106]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 20, 128)        │     9,807,104 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 256)            │       394,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 76618)          │    19,690,826 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 29,892,170 (114.03 MB)

 Trainable params: 29,892,170 (114.03 MB)

 Non-trainable params: 0 (0.00 B)

In [107]:
early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=3,
    restore_best_weights=True,
    verbose=1
)

reduce_lr = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=2,
    min_lr=1e-6,
    verbose=1
)

checkpoint = ModelCheckpoint(
    "best_model.keras",
    monitor="val_loss",
    save_best_only=True,
    verbose=1
)

In [108]:
history = model.fit(train_dataset, validation_data=valid_dataset, epochs=config["epochs"],callbacks=[ early_stopping, reduce_lr, checkpoint], verbose=1)

Epoch 1/10
29666/29666 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.1459 - loss: 6.7704
Epoch 1: val_loss improved from None to 6.10637, saving model to best_model.keras

Epoch 1: finished saving model to best_model.keras
29666/29666 ━━━━━━━━━━━━━━━━━━━━ 1106s 37ms/step - accuracy: 0.1791 - loss: 6.2832 - val_accuracy: 0.2065 - val_loss: 6.1064 - learning_rate: 0.0010
Epoch 2/10
29666/29666 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.2173 - loss: 5.5285
Epoch 2: val_loss improved from 6.10637 to 6.07560, saving model to best_model.keras

Epoch 2: finished saving model to best_model.keras
29666/29666 ━━━━━━━━━━━━━━━━━━━━ 1097s 37ms/step - accuracy: 0.2244 - loss: 5.4510 - val_accuracy: 0.2133 - val_loss: 6.0756 - learning_rate: 0.0010
Epoch 3/10
29665/29666 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.2414 - loss: 5.1182
Epoch 3: val_loss did not improve from 6.07560
29666/29666 ━━━━━━━━━━━━━━━━━━━━ 1086s 37ms/step - accuracy: 0.2472 - loss: 5.0522 - val_accuracy: 0.2114 - val_loss: 6.1790 - learning_rate: 0.0010
Epoch 4/10
29665/29666 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.2614 - loss: 4.7891
Epoch 4: ReduceLROnPlateau reducing learning rate to 0.0005000000237487257.

Epoch 4: val_loss did not improve from 6.07560
29666/29666 ━━━━━━━━━━━━━━━━━━━━ 1084s 37ms/step - accuracy: 0.2670 - loss: 4.7361 - val_accuracy: 0.2063 - val_loss: 6.3795 - learning_rate: 0.0010
Epoch 5/10
29665/29666 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.2924 - loss: 4.3344
Epoch 5: val_loss did not improve from 6.07560
29666/29666 ━━━━━━━━━━━━━━━━━━━━ 1090s 37ms/step - accuracy: 0.3072 - loss: 4.1798 - val_accuracy: 0.2013 - val_loss: 6.6227 - learning_rate: 5.0000e-04
Epoch 5: early stopping
Restoring model weights from the end of the best epoch: 2.

2026/07/26 15:09:38 WARNING mlflow.utils.autologging_utils: Encountered unexpected error during tensorflow autologging: INVALID_PARAMETER_VALUE: Response: {'error_code': 'INVALID_PARAMETER_VALUE'}

In [109]:
best_model = tf.keras.models.load_model("best_model.keras")
test_loss, test_accuracy = best_model.evaluate(test_dataset)
print(f"Test Loss     : {test_loss:.4f}")
print(f"Test Accuracy : {test_accuracy:.4f}")
perplexity = np.exp(test_loss)
print(f"Test Perplexity: {perplexity:.2f}")

3495/3495 ━━━━━━━━━━━━━━━━━━━━ 65s 18ms/step - accuracy: 0.2145 - loss: 6.1288
Test Loss     : 6.1288
Test Accuracy : 0.2145
Test Perplexity: 458.86